name = "dnssec-offchain-gateway"
compatibility_date = "2022-06-20"
account_id = "de97cd2a1370a6ed2ad759f894179bff"
main = "./src/index.ts"
node_compat = true

[dev]
port = 8000

[build]
command = "yarn build"
